public without sharing class APP_ProfissionalController {

    /*
    // Retorna lista de agendamentos por período
    @AuraEnabled(cacheable=false)
    public static List<APP_ProfissionalListResponseDTO> buscarAgendamentosFiltrados(Integer page, Integer count, String dateStart, String dateEnd) {
        return APP_ProfissionalService.listarAgendamentosFiltrados(page, count, dateStart, dateEnd);
    }

    // Retorna agendamentos por prontuário
    @AuraEnabled(cacheable=false)
    public static APP_ProfissionalListResponseDTO buscarAgendamentoPorProntuario(String prontuario) {
        return APP_ProfissionalService.listarAgendamento(prontuario);
    }
        */
}