public class APP_AberturaCasosPlusSoftDTO {
    public String plusSoftId;
    public String caseoriginid;
    public String casetypereasonid;
    
    public APP_AberturaCasosPlusSoftDTO(String plusSoftId, String casetypereasonid) {
        this.plusSoftId = plusSoftId;
        this.casetypereasonid = casetypereasonid;
        // this.casetext = 'Teste de envio de motivo';//casetext;
        this.caseoriginid = '3';//caseoriginid;
    }
   
}