public class EventVO {

    public String meetingStatusValues {get; set;}
    public DateTime startDate {get; set;}
    public DateTime endDate {get; set;}
    public List<String> selected {get; set;}
    public String typeValue {get; set;}
    public String communicationChannelValue {get; set;}
    public String subjectValue {get; set;}
    public String description {get; set;}
    // public String recurrenceValue {get; set;}
    public String actionValue {get; set;}
    public String medicTypeValue {get; set;}
    public String advisorPanelValue {get; set;}
    public List<String> contactIds {get; set;}

}